name: kffl
channels:
  - conda-forge
  - omnia
  - rdkit
  - samoturk
dependencies:
  - biopandas
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - rdkit
  - parmed  
  - pmw
  - pymol
  - python>=3.6.8
  - scikit-learn
  - seaborn
