name: kffl
channels:
  - conda-forge
  - omnia
  - rdkit
  - schrodinger
dependencies:
  - biopandas
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - rdkit=2019.03.2
  - parmed  
  - pymol
  - python=3.6.8
  - scikit-learn
  - seaborn
