name: kffl
channels:
  - conda-forge
  - omnia
  - rdkit
  - samoturk
  - schrodinger
dependencies:
  - pytest
  - biopandas
  - jupyter
  - matplotlib
  - numpy
  - pandas= 2.1
  - rdkit=2021.09
  - parmed  
  - pmw
  - pymol-bundle 
  - python>=3.9
  - scikit-learn
  - seaborn
